import { auth } from '@clerk/nextjs/server';
import Link from 'next/link';
import Image from 'next/image';
import Navbar from '@/components/Navbar';

export default async function Home() {
  const { userId } = await auth();

  return (
    <div className="min-h-screen flex flex-col bg-white">
      <Navbar />
      
      <main className="flex-1">
        <div className="container mx-auto px-4 ">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Left Content */}
            <div className="space-y-8">
              <h1 className="text-8xl font-bold bg-gradient-to-r from-pink-400 via-pink-300 to-orange-400 text-transparent bg-clip-text">
                <span className="bg-gradient-to-r from-oasis-purple via-pink-300 to-orange-400 text-transparent bg-clip-text">Ask Oasis</span>{' '}
               
              </h1>
              
              <div className="space-y-6">
                <p className="text-lg text-gray-600 leading-relaxed">
                  The "Ask Oasis" AI chatbot is designed to provide general information
                  related to fertility, reproductive health, and related services.
                </p>
                <p className="text-lg text-gray-600 leading-relaxed">
                  However, the content generated by the chatbot is for informational
                  purposes only and does not constitute professional medical advice,
                  diagnosis, or treatment.
                </p>
                <Link 
                  href="#"
                  className="inline-block text-gray-600 underline hover:text-[#874487] transition-colors"
                >
                  Read more.
                </Link>
              </div>

              <Link 
                href={"/chat" }
                className="inline-block px-10 py-3 bg-[#ff8484] text-white rounded-full hover:bg-[#ff8484] transition-colors transform hover:-translate-y-0.5 hover:shadow-lg"
              >
                {userId ? "Start Chat" : "Sign In"}
              </Link>
            </div>

            {/* Right Image */}
            <div className="relative">
              <div className="aspect-square  ">
                <Image
                  src="/BGImage.webp"
                  alt="Happy Family"
                  width={600}
                  height={600}
                  className="object-cover"
                  priority
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
