// import { auth } from '@clerk/nextjs';
import Link from 'next/link';
import Image from 'next/image';
import Navbar from '@/components/Navbar';

export default async function Home() {
  // const { userId } = auth();

  return (
    <div className="min-h-screen flex flex-col bg-white">
      <Navbar />
      
      <main className="flex-1">
        <div className="container mx-auto px-4 py-16">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Left Content */}
            <div className="space-y-8">
              <h1 className="text-6xl font-light">
                <span className="text-[#874487]">Ask</span>{' '}
                <span className="text-[#FF9B9B]">Oasis</span>
              </h1>
              
              <div className="space-y-6">
                <p className="text-lg text-gray-600 leading-relaxed">
                  The "Ask Oasis" AI chatbot is designed to provide general information
                  related to fertility, reproductive health, and related services.
                </p>
                <p className="text-lg text-gray-600 leading-relaxed">
                  However, the content generated by the chatbot is for informational
                  purposes only and does not constitute professional medical advice,
                  diagnosis, or treatment.
                </p>
                <Link 
                  href="#"
                  className="inline-block text-gray-600 underline hover:text-[#874487] transition-colors"
                >
                  Read more.
                </Link>
              </div>

              {/* <Link 
                href={userId ? "/chat" : "/sign-in"}
                className="inline-block px-10 py-3 bg-[#FF9B9B] text-white rounded-full hover:bg-[#ff8484] transition-colors transform hover:-translate-y-0.5 hover:shadow-lg"
              >
                {userId ? "Start Chat" : "Sign In"}
              </Link> */}
            </div>

            {/* Right Image */}
            <div className="relative">
              <div className="aspect-square rounded-full bg-[#FFE5E5] overflow-hidden shadow-2xl">
                <Image
                  src="/BGImage.webp"
                  alt="Happy Family"
                  width={600}
                  height={600}
                  className="object-cover"
                  priority
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
